[package]
name = "wvp-server"
version = "0.1.0"
authors = ["Maxwell Anderson, Caleb McDonald, Angelina Wanderlingh"]
edition = "2018"
license = "MIT"
repository = "https://github.com/Zaechus/waterguns-vs-paperplanes"

[workspace]
members = [
    "crate"
]

[dependencies]
rocket = "0.4"